name: Validación de CSS

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar código
      uses: actions/checkout@v3

    - name: Instalar CSS Validator
      run: npm install -g css-validator

    - name: Validar archivo CSS
      run: css-validator ./estilos.css
